In [1]:
import pandas as pd
from sklearn.datasets import load_wine


wine = load_wine()

df = pd.concat(
    [
        pd.DataFrame(wine.data, columns = wine.feature_names),
        pd.DataFrame(wine.target, columns = ["wine_type"])
    ],
    axis = 1
)

df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,wine_type
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [2]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size = 0.2, stratify = df['wine_type'], random_state = 42)

In [3]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range = (0, 1))
scaled_train = pd.concat(
    [
        pd.DataFrame(
            scaler.fit_transform(
                train.drop('wine_type', axis = 1),
                train['wine_type']
            ),
            columns = train.drop('wine_type', axis = 1).columns,
            index = train.index
        ),
        train['wine_type']
    ],
    axis = 1
)

pd.DataFrame(scaled_train)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,wine_type
36,0.592105,0.177866,0.795699,0.252577,0.434783,0.558621,0.688235,0.42,0.297468,0.283276,0.495935,0.569811,0.486661,0
30,0.710526,0.150198,0.720430,0.613402,0.336957,0.696552,0.855882,0.32,0.620253,0.377133,0.577236,0.543396,0.814066,0
26,0.621053,0.203557,0.677419,0.283505,0.250000,0.644828,0.764706,0.42,0.325949,0.300341,0.357724,0.735849,0.741310,0
12,0.715789,0.195652,0.564516,0.278351,0.206522,0.558621,0.711765,0.32,0.439873,0.368601,0.544715,0.615094,0.842361,0
148,0.602632,0.494071,0.548387,0.561856,0.239130,0.327586,0.123529,0.64,0.262658,0.609215,0.056911,0.132075,0.300728,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,0.655263,0.480237,0.731183,0.664948,0.293478,0.196552,0.052941,0.74,0.041139,0.261945,0.333333,0.298113,0.195635,2
87,0.163158,0.183794,0.677419,0.793814,0.195652,0.324138,0.373529,0.54,0.291139,0.112628,0.715447,0.732075,0.229588,1
34,0.652632,0.209486,0.693548,0.432990,0.434783,0.472414,0.644118,0.32,0.354430,0.249147,0.504065,0.603774,0.660469,0
163,0.507895,0.535573,0.532258,0.407216,0.391304,0.141379,0.105882,0.54,0.164557,0.341297,0.162602,0.181132,0.320938,2
131,0.486842,0.444664,0.559140,0.484536,0.369565,0.110345,0.258824,0.22,0.129747,0.351536,0.211382,0.056604,0.203719,2

In [4]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(scaled_train.drop('wine_type', axis = 1), scaled_train['wine_type'])

MultinomialNB()

In [5]:
test_scaled = pd.concat(
    [
        pd.DataFrame(
            scaler.transform(
                test.drop('wine_type', axis = 1)
            ),
            columns =  test.drop('wine_type', axis = 1).columns,
            index =  test.drop('wine_type', axis = 1).index
        ),
        test['wine_type']
    ],
    axis = 1
)

test_scaled

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,wine_type
10,0.807895,0.280632,0.505376,0.381443,0.380435,0.679310,0.876471,0.18,0.620253,0.381399,0.626016,0.716981,0.995958,0
134,0.389474,0.098814,0.478495,0.355670,0.163043,0.351724,0.070588,0.94,0.262658,0.355802,0.219512,0.090566,0.300728,2
28,0.747368,0.229249,0.774194,0.453608,0.402174,0.679310,0.773529,0.48,0.424051,0.274744,0.626016,0.803774,0.514956,0
121,0.139474,0.258893,1.005376,0.922680,0.532609,0.758621,1.394118,0.68,0.458861,0.402730,0.365854,0.913208,0.151172,1
62,0.694737,0.100791,0.301075,0.381443,0.260870,0.386207,0.426471,0.38,0.098101,0.215017,0.609756,0.449057,0.284559,1
51,0.736842,0.179842,0.666667,0.340206,0.260870,0.506897,0.779412,0.18,0.591772,0.368601,0.617886,0.792453,0.797898,0
7,0.797368,0.278656,0.672043,0.360825,0.554348,0.558621,0.638235,0.36,0.262658,0.321672,0.471545,0.871698,0.822150,0
66,0.547368,0.053360,0.182796,0.226804,0.086957,0.689655,0.835294,0.26,0.588608,0.343003,0.520325,0.720755,0.181083,1
129,0.265789,0.703557,0.548387,0.587629,0.108696,0.386207,0.414706,0.58,0.294304,0.112628,0.252033,0.490566,0.244139,1
166,0.636842,0.584980,0.666667,0.639175,0.445652,0.248276,0.170588,0.60,0.329114,0.802048,0.300813,0.109434,0.337106,2
102,0.344737,0.337945,0.591398,0.536082,0.304348,0.544828,0.520588,0.42,0.281646,0.129693,0.260163,0.796226,0.129345,1
143,0.681579,0.832016,0.532258,0.484536,0.239130,0.351724,0.135294,0.68,0.189873,0.266212,0.349593,0.294340,0.219887,2
42,0.750000,0.227273,0.661290,0.226804,0.336957,0.782759,0.947059,0.08,0.405063,0.354096,0.325203,0.864151,0.660469,0
130,0.481579,0.120553,0.516129,0.381443,0.565217,0.182759,0.267647,0.16,0.164557,0.240614,0.227642,0.007547,0.284559,2
14,0.881579,0.223320,0.548387,0.072165,0.347826,0.800000,0.970588,0.32,0.803797,0.530717,0.585366,0.652830,1.025869,0
108,0.313158,0.108696,0.311828,0.432990,0.239130,0.475862,0.500000,0.52,0.525316,0.121160,0.308943,0.660377,0.027486,1
105,0.365789,0.357708,0.489247,0.587629,0.217391,0.241379,0.441176,1.06,0.316456,0.121160,0.308943,0.766038,0.029911,1
20,0.797368,0.175889,0.494624,0.278351,0.608696,0.696552,0.832353,0.22,0.531646,0.372867,0.495935,0.920755,0.405821,0
100,0.276316,0.264822,0.182796,0.355670,0.293478,0.431034,0.538235,0.26,0.310127,0.172355,0.642276,0.637736,0.349232,1
38,0.536842,0.150198,0.397849,0.252577,0.304348,0.489655,0.676471,0.30,0.300633,0.206485,0.569106,0.535849,0.599838,0
93,0.331579,0.413043,0.462366,0.381443,0.195652,0.506897,0.561765,0.24,0.496835,0.074232,0.544715,0.766038,0.009701,1
60,0.342105,0.071146,0.494624,0.278351,0.336957,0.368966,0.220588,1.00,-0.003165,0.169795,0.626016,0.150943,0.324980,1
22,0.705263,0.221344,0.537634,0.309278,0.336957,0.562069,0.747059,0.28,0.401899,0.215017,0.512195,1.030189,0.611964,0
18,0.831579,0.167984,0.602151,0.304124,0.413043,0.800000,1.055882,0.38,0.455696,0.633106,0.609756,0.584906,1.133387,0
98,0.352632,0.065217,0.397849,0.407216,0.195652,0.875862,1.002941,0.22,0.484177,0.274744,0.455285,0.566038,0.308812,1
64,0.300000,0.140316,0.629032,0.432990,0.369565,0.313793,0.414706,0.64,0.193038,0.142491,0.788618,0.362264,0.062247,1
58,0.707895,0.136364,0.612903,0.314433,0.413043,0.834483,0.979412,0.12,0.512658,0.470990,0.333333,0.603774,0.814066,0
132,0.468421,0.310277,0.559140,0.690722,0.304348,0.058621,0.220588,0.28,0.129747,0.377133,0.146341,0.033962,0.227971,2
112,0.192105,0.383399,0.838710,0.484536,0.358696,0.265517,0.497059,0.94,0.199367,0.215017,0.609756,0.464151,0.265966,1
155,0.563158,0.879447,0.516129,0.587629,0.250000,0.262069,0.085294,0.96,0.357595,0.564846,0.097561,0.079245,0.361358,2
48,0.807895,0.252964,0.559140,0.422680,0.358696,0.610345,0.758824,0.38,0.620253,0.419795,0.479675,0.558491,0.632175,0
176,0.563158,0.365613,0.543011,0.484536,0.543478,0.231034,0.100000,0.80,0.329114,0.684300,0.097561,0.132075,0.454325,2
94,0.155263,0.247036,0.494624,0.381443,0.304348,0.703448,0.564706,0.08,0.294304,0.168089,0.552846,0.637736,0.054163,1
177,0.815789,0.664032,0.741935,0.716495,0.282609,0.368966,0.123529,0.86,0.294304,0.675768,0.105691,0.124528,0.227971,2
164,0.723684,0.399209,0.505376,0.587629,0.217391,0.127586,0.100000,0.56,0.193038,0.708191,0.178862,0.154717,0.272433,2
173,0.705263,0.970356,0.586022,0.510309,0.271739,0.241379,0.079412,0.78,0.202532,0.547782,0.130081,0.177358,0.373484,2

In [6]:
comparison = pd.concat(
    [
        pd.DataFrame(
            model.predict(
                test_scaled.drop('wine_type', axis = 1)
            ),
            columns = ['predicted_wine_type'],
        ),
        test_scaled['wine_type'].rename('actual_wine_type').reset_index(drop = True)
    ],
    axis = 1
)

comparison

    predicted_wine_type  actual_wine_type
0                     0                 0
1                     2                 2
2                     1                 0
3                     1                 1
4                     1                 1
5                     0                 0
6                     0                 0
7                     1                 1
8                     1                 1
9                     2                 2
10                    1                 1
11                    2                 2
12                    0                 0
13                    0                 2
14                    0                 0
15                    1                 1
16                    1                 1
17                    0                 0
18                    1                 1
19                    0                 0
20                    1                 1
21                    1                 1
22                    0                 0
23                    0                 0
24                    1                 1
25                    1                 1
26                    0                 0
27                    2                 2
28                    1                 1
29                    2                 2
30                    0                 0
31                    2                 2
32                    1                 1
33                    2                 2
34                    2                 2
35                    2                 2

In [7]:
model.score(test_scaled.drop('wine_type', axis = 1), test_scaled['wine_type'])

0.9444444444444444